<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            [
                'id' => 'GlW3GhOBkbu2gtJwr6jH',
                'title' => 'Auto',
                'image' => 'https://firebasestorage.googleapis.com/v0/b/coming-bro.appspot.com/o/images%2FAuto_1737448319724.jpg?alt=media&token=130f36b8-8036-4f7b-aea2-a7351a97119a',
                'enable' => true,
                'offer_rate' => false,
                'intercity_type' => true,
                'is_ac_non_ac' => false,
                'basic_fare_charges' => '50',
                'basic_fare_km' => '2',
                'km_charge' => null,
                'non_ac_km_charge' => '21',
                'ride_time_fare_per_minute' => '0',
                'holding_charge_minute' => '10',
                'holding_charges' => '20',
                'night_fare_charge' => '26',
                'start_night_time' => '23:00',
                'end_night_time' => '05:00',
                'admin_commission' => '{"isEnabled": false, "type": "fix", "amount": "0"}',
            ],
            [
                'id' => 'JCH5ciDxfOeuQDX2nbyZ',
                'title' => 'Cab ',
                'image' => 'https://firebasestorage.googleapis.com/v0/b/coming-bro.appspot.com/o/images%2FMini_1737448261921.jpg?alt=media&token=ef219c4a-788e-4355-a24d-a41086ea4f95',
                'enable' => true,
                'offer_rate' => false,
                'intercity_type' => true,
                'is_ac_non_ac' => true,
                'basic_fare_charges' => '50',
                'basic_fare_km' => '2',
                'km_charge' => '25',
                'non_ac_km_charge' => '21',
                'ride_time_fare_per_minute' => '0',
                'holding_charge_minute' => '1',
                'holding_charges' => '2',
                'night_fare_charge' => '0.8',
                'start_night_time' => '23:00',
                'end_night_time' => '05:00',
                'admin_commission' => '{"isEnabled": false, "type": "fix", "amount": "0"}',
            ],
            [
                'id' => 'VXmBuNgKxOomZzc8iOgV',
                'title' => ' Sedan',
                'image' => 'https://firebasestorage.googleapis.com/v0/b/coming-bro.appspot.com/o/images%2FMini%20Sedan_1742539135739.jpg?alt=media&token=b461c8d7-9da9-47d5-9193-d964a4444412',
                'enable' => true,
                'offer_rate' => false,
                'intercity_type' => true,
                'is_ac_non_ac' => true,
                'basic_fare_charges' => '90',
                'basic_fare_km' => '2',
                'km_charge' => '25',
                'non_ac_km_charge' => '21',
                'ride_time_fare_per_minute' => '1',
                'holding_charge_minute' => '30',
                'holding_charges' => '50',
                'night_fare_charge' => '1.5',
                'start_night_time' => '22:00',
                'end_night_time' => '05:00',
                'admin_commission' => '{"isEnabled": false, "type": "fix", "amount": "0"}',
            ],
            [
                'id' => 'as88LY9F81bNXOWi5qaR',
                'title' => 'T T',
                'image' => 'https://firebasestorage.googleapis.com/v0/b/coming-bro.appspot.com/o/images%2FTempo%20Traveller_1742308472602.jpg?alt=media&token=f37e5dc2-2ab9-4b4d-9e5d-87731586d75f',
                'enable' => false,
                'offer_rate' => false,
                'intercity_type' => true,
                'is_ac_non_ac' => true,
                'basic_fare_charges' => '100',
                'basic_fare_km' => '3',
                'km_charge' => '10',
                'non_ac_km_charge' => '24',
                'ride_time_fare_per_minute' => '0',
                'holding_charge_minute' => '0',
                'holding_charges' => '0',
                'night_fare_charge' => '0',
                'start_night_time' => '22:00',
                'end_night_time' => '05:00',
                'admin_commission' => '{"isEnabled": false, "type": "fix", "amount": "0"}',
            ],
            [
                'id' => 'cWlkB4ZEOWwlplkMOkPj',
                'title' => 'testing',
                'image' => 'https://firebasestorage.googleapis.com/v0/b/coming-bro.appspot.com/o/images%2Fdocument_1741865222974.png?alt=media&token=67780dbc-6b8d-4652-8815-b8734d25aae9',
                'enable' => false,
                'offer_rate' => false,
                'intercity_type' => false,
                'is_ac_non_ac' => false,
                'basic_fare_charges' => '12',
                'basic_fare_km' => '12',
                'km_charge' => '16',
                'non_ac_km_charge' => '10',
                'ride_time_fare_per_minute' => '12',
                'holding_charge_minute' => '10',
                'holding_charges' => '10',
                'night_fare_charge' => '2',
                'start_night_time' => '00:00',
                'end_night_time' => '08:00',
                'admin_commission' => '{"isEnabled": false, "type": "fix", "amount": "12"}',
            ],
            [
                'id' => 'slb7TOd3StLENu9YQJnv',
                'title' => 'test',
                'image' => '',
                'enable' => false,
                'offer_rate' => false,
                'intercity_type' => true,
                'is_ac_non_ac' => true,
                'basic_fare_charges' => '10',
                'basic_fare_km' => '10',
                'km_charge' => '10',
                'non_ac_km_charge' => '20',
                'ride_time_fare_per_minute' => '10',
                'holding_charge_minute' => '5',
                'holding_charges' => '5',
                'night_fare_charge' => '2',
                'start_night_time' => '12:47',
                'end_night_time' => '15:50',
                'admin_commission' => '{"isEnabled": false, "type": "fix", "amount": "10"}',
            ],
            [
                'id' => 'vGIpx48e4L5KgW55M5FW',
                'title' => 'Suv',
                'image' => 'https://firebasestorage.googleapis.com/v0/b/coming-bro.appspot.com/o/images%2FErtiga_1742309304548.jpg?alt=media&token=57345c24-3650-4783-bfe7-3c8762055150',
                'enable' => true,
                'offer_rate' => false,
                'intercity_type' => true,
                'is_ac_non_ac' => true,
                'basic_fare_charges' => '90',
                'basic_fare_km' => '2',
                'km_charge' => '25',
                'non_ac_km_charge' => '21',
                'ride_time_fare_per_minute' => '1',
                'holding_charge_minute' => '30',
                'holding_charges' => '50',
                'night_fare_charge' => '1.5',
                'start_night_time' => '22:00',
                'end_night_time' => '05:00',
                'admin_commission' => '{"isEnabled": false, "type": "fix", "amount": "0"}',
            ]
        ];

        foreach ($records as $record) {
            DB::table('services')->updateOrInsert(['id' => $record['id']], $record);
        }
    }
}
